### ISSUE TITLE
def line1(x,y) and def line2(x,y)

### ISSUE THREAD

**Issue by easternmie** [anandsinghkunwar/pedestrian-counter#1]
Hi @anandsinghkunwar, can you explain to me more about this lines of code?

```
def line1(x,y):
    return y - (29*x)/96.0 - 300

def line2(x,y):
    return y - (29*x)/96.0 - 500
```

I believe its related to this code (create two lines on the frame)

```
    cv2.line(frame, (0,300), (1920,880), (255, 0, 0), 4)
    cv2.line(frame, (0,500), (1920,1080), (255, 0, 0), 4)
```

If I want to change the code above to (which is two lines transverse the frame)

```
    cv2.line(frame, (0,100), (500,100), (255, 0, 0), 4)
    cv2.line(frame, (0,200), (500,200), (255, 0, 0), 4)
```

How can I modify the function `line1()` and `line2()`

Can you help me sir?

**Comment by easternmie** [comment]
I already got the answer, its related to formula y=mx+c. thanks anand for sharing this code. really interesting.

**Comment by anandsinghkunwar** [comment]
The line1 and line2 functions are used determine whether a point is between the two lines specified or not. @easternmie Yeah you are right, it is exactly y=mx+c. You need to tweak line1 and line2 parameters to change the lines of reference and also the cv2.line parameters for reflecting the changed line in a visual. Do send a pull request if you made some improvements.

**Comment by vijjubadshah** [comment]
def line1(x,y):
    return y - (29*x)/96.0 - 300

It is Base on y=mx+c
In above line (29x/96) is mx So m=29/96
"m" Stand for  Slope of a line
m= (y2-y1)/(x2-x1)

Example
 cv2.line(frame, (200,0), (1920,980), (255, 0, 0), 4)

here  [200,0]  x1=200 and y1=0
         [1920,980]  x2=1920 and y2=980
C=y1=0
So m= (y2-y1)/(x2-x1)
         = (980-0)/(1920-200)
         =0.569767441
         =49,86

def line1(x,y):
return y - (49*x)/86.0 - 0

Hope it will Help You...
