### ISSUE TITLE
How to user this code with a camera device?

### ISSUE THREAD

**Issue by albertyou2** [anandsinghkunwar/pedestrian-counter#2]
@anandsinghkunwar hi
could this code be use for live stream data from cemera?
Thank you very much !

**Comment by anandsinghkunwar** [comment]
Hi @albertyou2, sorry for the delay. In order to capture from your webcam change line 4 of `pedesetrian.py` from
```
cap = cv2.VideoCapture('TownCentreXVID.avi')
```
to
```
cap = cv2.VideoCapture(0)
```
Hope it helps :smile:

**Comment by albertyou2** [comment]
THANK YOU VERY MUCH

**Comment by anandsinghkunwar** [comment]
Do send a pull request if you made some improvements. Cheers.

**Comment by albertyou2** [comment]
@anandsinghkunwar 
i have tried your code these days. it works fine !
But I have a question here. will the angel that i put the camera to heavily effect the result ?

**Comment by anandsinghkunwar** [comment]
@albertyou2
The angle will definitely affect the result, you'll need to fine tune according to your video. It will work best with a top angle(view from top), where the pedestrians will form separate blobs.

**Comment by albertyou2** [comment]
@anandsinghkunwar 
Got it，thanks！
i will do some experiments based on your work.

**Comment by albertyou2** [comment]
@anandsinghkunwar 
I have tried your code with a camera ,the detection result is good!
But I want to modify your code for  my problem now.The angle is different with your video given.
So i read your code carefully.
The two "lines" in your code confuse me :
#linses are here in your code :
def line1(x,y):
    return y - (29*x)/96.0 - 300
def line2(x,y):
    return y - (29*x)/96.0 - 500

I do not know the  purpose of  these codes. and i aslo confuse about these codes below:
if line1(xnew, ynew) > 0 and line2(xnew, ynew) < 0:
            pointInMiddle.add(point) 
Does "point in middle" means a lot of  points are between two lines drawed in the video?
it seems that you don't use them after add them to a set.

Could you please give a gereral idea about the tracking and counting of your work？
Thank you !
