### ISSUE TITLE
Line cross

### ISSUE THREAD

**Issue by israfila3** [anandsinghkunwar/pedestrian-counter#3]
return y - (29*x)/96.0 - 300

i have tried to understand but didn't get anything
Can you please explain why "29" and "96" is used?

**Comment by vijjubadshah** [comment]
def line1(x,y):
return y - (29*x)/96.0 - 300

It is Base on y=mx+c
In above line (29x/96) is mx So m=29/96
"m" Stand for Slope of a line
m= (y2-y1)/(x2-x1)

Example
cv2.line(frame, (200,0), (1920,980), (255, 0, 0), 4)

here [200,0] x1=200 and y1=0
[1920,980] x2=1920 and y2=980
C=y1=0
So m= (y2-y1)/(x2-x1)
= (980-0)/(1920-200)
=0.569767441
=49,86

def line1(x,y):
return y - (49*x)/86.0 - 0

Hope it will Help You...
